### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [jasonchaffee/chaffee.zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

**Comment by jasonchaffee** [comment]
Done.

**Comment by jasonchaffee** [comment]
Added some more documentation and screenshot with all languages installed.

**Comment by unixorn** [comment]
Added in https://github.com/unixorn/awesome-zsh-plugins/pull/669
